upstream moon_backend {
    server 172.18.0.6:8080;
    keepalive 32;
}
upstream moon_frontend {
    server 172.18.0.7:3000;
    keepalive 16;
}
limit_req_zone $binary_remote_addr zone=moon_limit:10m rate=30r/s;
